# This file should be used as gitignore in real work
spring:
  datasource:
    password: '1234'

jwt:
  secret: 'VGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCBhdXRoZW50aWNhdGlvbiB3aGljaCBzaG91bGQgYmUgc3Ryb25nIGFuZCBsb25nLg=='
  expiration-in-ms: '3600000'

  # --- 카카오 로그인 설정 추가 ---
kakao:
  client-id: "5bc58dc97e51205b93b0e4f32ace1d4a"
  client-secret: "0sTsA1y0paSXrVROeFo4xv3FR6UsbsAe"
  redirect-uri: "http://localhost:8080/api/v1/auth/kakao/callback" # AuthController에 설정된 콜백 URL
  token-uri: "https://kauth.kakao.com/oauth/token"
  user-info-uri: "https://kapi.kakao.com/v2/user/me"
  auth-uri: "https://kauth.kakao.com/oauth/authorize"
