server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles:
    include: secret # Call with file : application-secret.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mingleup?serverTimezone=Asia/Seoul
    username: root
  jpa:
    defer-datasource-initialization: true # Delay data.sql execution time to after DB initialization
    database-platform: org.hibernate.dialect.MySQLDialect # Use MYSQL dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:dummy}
      secret-key: ${AWS_SECRET_ACCESS_KEY:dummy}
    region: ap-northeast-2
    s3:
      bucket: mingleup-bucket-name
