server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles:
    include: secret # Call with file : application-secret.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mingleup-db:3306/mingleup-db?serverTimezone=Asia/Seoul&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
  messages:
    encoding: UTF-8

  jpa:
    defer-datasource-initialization: true # Delay data.sql execution time to after DB initialization
    database-platform: org.hibernate.dialect.MySQLDialect # Use MYSQL dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect




