services:
  mingleup-db:
    image: mysql:8.4.7
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - mingleup-net
    restart: always
    expose:
      - "3306"

  spring-service:
    image: ${DOCKER_USERNAME}/spring-service:latest
    depends_on:
      - mingleup-db
    environment:
      # 1. DB 설정 (기존)
      SPRING_DATASOURCE_URL: jdbc:mysql://mingleup-db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      
      # 2. AWS S3 설정 (추가)
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      
      # 3. JWT & Kakao & BaseURL 설정 (추가)
      JWT_SECRET: ${JWT_SECRET}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      BASE_URL: ${BASE_URL}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
    ports:
      - "8080:8080"
    networks:
      - mingleup-net
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  mingleup-net: {}


